---
vault_posthog_api_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          39613264306632663132336130373934353366376563356434363061393934343162653234643533
          3035386434643532356635303933326631666137313532320a333766333230663133616139306131
          34333536363130626339616564386435306664323438653162346665386634303766623565393262
          3362366462643264370a613237313266666466623531653834313364373137343239393335373661
          35376266643335393137623438353836343739393434653437333436626134663336373364653036
          3430623061386466343565333936616638333663383532386331
vault_posthog_project_id: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          66623263633139356465653337373339316534366232373764303733623930363436613533643265
          6566373230636439383363656466326631663266376639320a383339646633343638383336313339
          31386131313139383934666632316164376662393038336538323836643964306435623966393839
          3836373231373762650a336436646337343663633664363935373863396438383035653864393865
          6364
vault_posthog_host: "https://app.posthog.com"
